### ISSUE TITLE
Как перевести фильтр на русский

### ISSUE THREAD

**Issue by OlegEgoism** [vb64/django.admin.filters#10]
https://github.com/vb64/django.admin.filters

Добрый! Подскажите как перевести текст на русский. Не работает то, что описано в инструкции.
![image](https://user-images.githubusercontent.com/81327146/214380095-62b46535-ad36-4c6a-a864-62ba96625758.png)
Делаю так.
![image](https://user-images.githubusercontent.com/81327146/214380146-7f45b286-572f-434f-9938-25c4f3fba2ab.png)

WIDGET_LOCALE = 'ru' менял не помогает. Как это исправить! Спасибо.

**Comment by OlegEgoism** [comment]
Приветствую.

Нужно создать свой класс, унаследовав его от нужного класса из библиотеки и переопределить необходимые атрибуты.

Вот [пример для DateRangePicker](https://github.com/vb64/django.admin.filters/blob/main/READMEru.md#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0-daterangepicker)

**Comment by vb64** [comment]
> WIDGET_LOCALE = 'ru' менял не помогает.

Данный атрибут задает язык, на котором отображаются названия месяцев и дней недели в календаре. По умолчанию он устанавливается в значение параметра LANGUAGE_CODE файла settings.py вашего проекта.
