### ISSUE TITLE
получить нажатие на булавку на карте  в django app

### ISSUE THREAD

**Issue by borunov** [vb64/django.admin.filters#11]
Я хочу по нажатию на объект на карте (на булавку) в другом окне показывать много свойств этого объекта. Подскажите, пожалуйста, можно это сделать (вызвать вьюху с соответствующим primary key) с помощью Вашей библиотеки? Если нет, буду признателен, если подскажете, в какую сторону читать.

**Comment by vb64** [comment]
Я растяпа, дал человеку ссылку не на тот репозитарий. Вопрос перенесен в репо библиотеки, к которой он относится:

https://github.com/vb64/django.admin.geomap/issues/39
