### ISSUE TITLE
Feature request: Dropdown select

### ISSUE THREAD

**Issue by eriktelepovsky** [vb64/django.admin.filters#24]
Hello. 

It would be great to have a filter field with dropdown select widget. Useful for filters with too many choices. 

Can you consider?

**Comment by vb64** [comment]
What about [regular Django admin select dropdown](https://stackoverflow.com/questions/69384417/django-admin-select-dropdown)?

**Comment by eriktelepovsky** [comment]
Yes. How to use it in filters?

**Comment by vb64** [comment]
There is an example by the link above.

**Comment by eriktelepovsky** [comment]
But that example is for ModelForm, not for filter in the list.

**Comment by vb64** [comment]
What do you mean by "filter in the list"?

Can you give a clear description for your use case?

**Comment by eriktelepovsky** [comment]
Well, this library adds new useful filters for DjangoAdminFilters. I suggested the new filter type "dropdown select" which is not available by default in Django. The link you sent just describes how to use selects in ModelAdmin (change form) not AdminFilters (in the list of objects).

**Comment by vb64** [comment]
Here is a [ready-made solution](https://github.com/mrts/django-admin-list-filter-dropdown) to this problem. 

Have you tried using it?

**Comment by vb64** [comment]
https://github.com/vb64/django.admin.filters#related-projects

**Comment by eriktelepovsky** [comment]
Yes, that works. Thank you!
